'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WebServiceMyActivation
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WebServiceMyActivation.MyActivationSoap")>  _
    Public Interface MyActivationSoap
        
        'CODEGEN: Generating message contract since element name PhoneNumber from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Activate", ReplyAction:="*")>  _
        Function Activate(ByVal request As WebServiceMyActivation.ActivateRequest) As WebServiceMyActivation.ActivateResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ActivateRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Activate", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WebServiceMyActivation.ActivateRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebServiceMyActivation.ActivateRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ActivateRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public PhoneNumber As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public HardwareSTR As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public IsServer As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public AppID As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public LicensePWD As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal PhoneNumber As String, ByVal HardwareSTR As String, ByVal IsServer As Boolean, ByVal AppID As Integer, ByVal LicensePWD As String)
            MyBase.New
            Me.PhoneNumber = PhoneNumber
            Me.HardwareSTR = HardwareSTR
            Me.IsServer = IsServer
            Me.AppID = AppID
            Me.LicensePWD = LicensePWD
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ActivateResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ActivateResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WebServiceMyActivation.ActivateResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebServiceMyActivation.ActivateResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ActivateResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ActivateResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ActivateResult As String)
            MyBase.New
            Me.ActivateResult = ActivateResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface MyActivationSoapChannel
        Inherits WebServiceMyActivation.MyActivationSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class MyActivationSoapClient
        Inherits System.ServiceModel.ClientBase(Of WebServiceMyActivation.MyActivationSoap)
        Implements WebServiceMyActivation.MyActivationSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WebServiceMyActivation_MyActivationSoap_Activate(ByVal request As WebServiceMyActivation.ActivateRequest) As WebServiceMyActivation.ActivateResponse Implements WebServiceMyActivation.MyActivationSoap.Activate
            Return MyBase.Channel.Activate(request)
        End Function
        
        Public Function Activate(ByVal PhoneNumber As String, ByVal HardwareSTR As String, ByVal IsServer As Boolean, ByVal AppID As Integer, ByVal LicensePWD As String) As String
            Dim inValue As WebServiceMyActivation.ActivateRequest = New WebServiceMyActivation.ActivateRequest()
            inValue.Body = New WebServiceMyActivation.ActivateRequestBody()
            inValue.Body.PhoneNumber = PhoneNumber
            inValue.Body.HardwareSTR = HardwareSTR
            inValue.Body.IsServer = IsServer
            inValue.Body.AppID = AppID
            inValue.Body.LicensePWD = LicensePWD
            Dim retVal As WebServiceMyActivation.ActivateResponse = CType(Me,WebServiceMyActivation.MyActivationSoap).Activate(inValue)
            Return retVal.Body.ActivateResult
        End Function
    End Class
End Namespace
