'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WebServiceUpdateUri
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://byte.com.ly/ByteUpdateSrv/", ConfigurationName:="WebServiceUpdateUri.wsSoap")>  _
    Public Interface wsSoap
        
        'CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://byte.com.ly/ByteUpdateSrv/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://byte.com.ly/ByteUpdateSrv/HelloWorld", ReplyAction:="*")>  _
        Function HelloWorld(ByVal request As WebServiceUpdateUri.HelloWorldRequest) As WebServiceUpdateUri.HelloWorldResponse
        
        'CODEGEN: Generating message contract since element name PCSec from namespace http://byte.com.ly/ByteUpdateSrv/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://byte.com.ly/ByteUpdateSrv/GetUpdateUrl", ReplyAction:="*")>  _
        Function GetUpdateUrl(ByVal request As WebServiceUpdateUri.GetUpdateUrlRequest) As WebServiceUpdateUri.GetUpdateUrlResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class HelloWorldRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="HelloWorld", [Namespace]:="http://byte.com.ly/ByteUpdateSrv/", Order:=0)>  _
        Public Body As WebServiceUpdateUri.HelloWorldRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebServiceUpdateUri.HelloWorldRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class HelloWorldRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class HelloWorldResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="HelloWorldResponse", [Namespace]:="http://byte.com.ly/ByteUpdateSrv/", Order:=0)>  _
        Public Body As WebServiceUpdateUri.HelloWorldResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebServiceUpdateUri.HelloWorldResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://byte.com.ly/ByteUpdateSrv/")>  _
    Partial Public Class HelloWorldResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public HelloWorldResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HelloWorldResult As String)
            MyBase.New
            Me.HelloWorldResult = HelloWorldResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetUpdateUrlRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetUpdateUrl", [Namespace]:="http://byte.com.ly/ByteUpdateSrv/", Order:=0)>  _
        Public Body As WebServiceUpdateUri.GetUpdateUrlRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebServiceUpdateUri.GetUpdateUrlRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://byte.com.ly/ByteUpdateSrv/")>  _
    Partial Public Class GetUpdateUrlRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public AppID As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public AppVersion As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public PCSec As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AppID As Integer, ByVal AppVersion As Integer, ByVal PCSec As String)
            MyBase.New
            Me.AppID = AppID
            Me.AppVersion = AppVersion
            Me.PCSec = PCSec
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetUpdateUrlResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetUpdateUrlResponse", [Namespace]:="http://byte.com.ly/ByteUpdateSrv/", Order:=0)>  _
        Public Body As WebServiceUpdateUri.GetUpdateUrlResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebServiceUpdateUri.GetUpdateUrlResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://byte.com.ly/ByteUpdateSrv/")>  _
    Partial Public Class GetUpdateUrlResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetUpdateUrlResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetUpdateUrlResult As String)
            MyBase.New
            Me.GetUpdateUrlResult = GetUpdateUrlResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface wsSoapChannel
        Inherits WebServiceUpdateUri.wsSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class wsSoapClient
        Inherits System.ServiceModel.ClientBase(Of WebServiceUpdateUri.wsSoap)
        Implements WebServiceUpdateUri.wsSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WebServiceUpdateUri_wsSoap_HelloWorld(ByVal request As WebServiceUpdateUri.HelloWorldRequest) As WebServiceUpdateUri.HelloWorldResponse Implements WebServiceUpdateUri.wsSoap.HelloWorld
            Return MyBase.Channel.HelloWorld(request)
        End Function
        
        Public Function HelloWorld() As String
            Dim inValue As WebServiceUpdateUri.HelloWorldRequest = New WebServiceUpdateUri.HelloWorldRequest()
            inValue.Body = New WebServiceUpdateUri.HelloWorldRequestBody()
            Dim retVal As WebServiceUpdateUri.HelloWorldResponse = CType(Me,WebServiceUpdateUri.wsSoap).HelloWorld(inValue)
            Return retVal.Body.HelloWorldResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WebServiceUpdateUri_wsSoap_GetUpdateUrl(ByVal request As WebServiceUpdateUri.GetUpdateUrlRequest) As WebServiceUpdateUri.GetUpdateUrlResponse Implements WebServiceUpdateUri.wsSoap.GetUpdateUrl
            Return MyBase.Channel.GetUpdateUrl(request)
        End Function
        
        Public Function GetUpdateUrl(ByVal AppID As Integer, ByVal AppVersion As Integer, ByVal PCSec As String) As String
            Dim inValue As WebServiceUpdateUri.GetUpdateUrlRequest = New WebServiceUpdateUri.GetUpdateUrlRequest()
            inValue.Body = New WebServiceUpdateUri.GetUpdateUrlRequestBody()
            inValue.Body.AppID = AppID
            inValue.Body.AppVersion = AppVersion
            inValue.Body.PCSec = PCSec
            Dim retVal As WebServiceUpdateUri.GetUpdateUrlResponse = CType(Me,WebServiceUpdateUri.wsSoap).GetUpdateUrl(inValue)
            Return retVal.Body.GetUpdateUrlResult
        End Function
    End Class
End Namespace
