'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GT1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _next() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("next", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _option() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("option", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''/****** Object:  StoredProcedure [dbo].[sp_tbl_Invoice_Insert]    Script Date: 09/07/2017 15:18:00 ******/
        '''IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[sp_tbl_Invoice_Insert]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        '''DROP PROCEDURE [dbo].[sp_tbl_Invoice_Insert]
        ''';
        '''/****** Object:  StoredProcedure [dbo].[sp_tbl_Invoice_Update]    Script Date: 09/07/2017 15:18:00 ******/
        '''IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[sp_tbl_Invoice_Update]&apos;) AND type in (N&apos;P&apos; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property a_All_Proc_Func() As String
            Get
                Return ResourceManager.GetString("a_All_Proc_Func", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''
        '''if not exists (Select * from Settings where SettingName = &apos;IsMultiExDateAllowed&apos;)
        '''insert into Settings (SettingName ,SettingValue ) values (&apos;IsMultiExDateAllowed&apos;,N&apos;false&apos;)
        '''
        '''if not exists (Select * from Settings where SettingName = &apos;IsPacketDefault&apos;)
        '''insert into Settings (SettingName ,SettingValue ) values (&apos;IsPacketDefault&apos;,N&apos;false&apos;)
        '''
        '''if not exists (Select * from Settings where SettingName = &apos;OwenerID&apos;)
        '''insert into Settings (SettingName ,SettingValue ) values (&apos;OwenerID&apos;,N&apos;&apos;)
        '''
        '''if not exists (S [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property a_Insert_All_Settings() As String
            Get
                Return ResourceManager.GetString("a_Insert_All_Settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to update Version set VersoinNumber = 4
        '''
        '''.
        '''</summary>
        Friend ReadOnly Property a_UpdateVersion4() As String
            Get
                Return ResourceManager.GetString("a_UpdateVersion4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to update Version set VersoinNumber = 5
        '''
        '''.
        '''</summary>
        Friend ReadOnly Property a_UpdateVersion5() As String
            Get
                Return ResourceManager.GetString("a_UpdateVersion5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to update Version set VersoinNumber = 6
        '''
        '''.
        '''</summary>
        Friend ReadOnly Property a_UpdateVersion6() As String
            Get
                Return ResourceManager.GetString("a_UpdateVersion6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /*
        '''   Sunday, September 17, 201712:16:52 PM
        '''   User: 
        '''   Server: (local)
        '''   Database: GT1
        '''   Application: 
        '''*/
        '''
        '''/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
        '''BEGIN TRANSACTION
        '''SET QUOTED_IDENTIFIER ON
        '''SET ARITHABORT ON
        '''SET NUMERIC_ROUNDABORT OFF
        '''SET CONCAT_NULL_YIELDS_NULL ON
        '''SET ANSI_NULLS ON
        '''SET ANSI_PADDING ON
        '''SET ANSI_WARNINGS ON
        '''COMMIT
        '''BEGIN TRANSACTION
        ''';
        '''ALTER TABLE dbo.Service        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property a01_Add_UserID_To_Services() As String
            Get
                Return ResourceManager.GetString("a01_Add_UserID_To_Services", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE TABLE [dbo].[Settings](
        '''	[SettingID] [bigint] IDENTITY(1,1) NOT NULL,
        '''	[SettingName] [nvarchar](200) NOT NULL,
        '''	[SettingValue] [nvarchar](200) NOT NULL,
        ''' CONSTRAINT [PK_Settings] PRIMARY KEY CLUSTERED 
        '''(
        '''	[SettingID] ASC
        ''')WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
        ''') ON [PRIMARY]
        '''
        '''
        '''
        '''.
        '''</summary>
        Friend ReadOnly Property a02_02_CREATE_TABLE_Settings() As String
            Get
                Return ResourceManager.GetString("a02_02_CREATE_TABLE_Settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to update Account 
        '''set AcountName = &apos;فواتير نقدية&apos;
        '''where AccountID = 1.
        '''</summary>
        Friend ReadOnly Property a02_03_Update_Account() As String
            Get
                Return ResourceManager.GetString("a02_03_Update_Account", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
        '''BEGIN TRANSACTION
        '''SET QUOTED_IDENTIFIER ON
        '''SET ARITHABORT ON
        '''SET NUMERIC_ROUNDABORT OFF
        '''SET CONCAT_NULL_YIELDS_NULL ON
        '''SET ANSI_NULLS ON
        '''SET ANSI_PADDING ON
        '''SET ANSI_WARNINGS ON
        '''COMMIT
        '''BEGIN TRANSACTION
        ''';
        '''CREATE UNIQUE NONCLUSTERED INDEX IX_Settings ON dbo.Settings
        '''	(
        '''	SettingName
        '''	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, AL [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property a02_04_CREATE_UNIQUE_NONCLUSTERED_INDEX_IX_Settings() As String
            Get
                Return ResourceManager.GetString("a02_04_CREATE_UNIQUE_NONCLUSTERED_INDEX_IX_Settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SET IDENTITY_INSERT [dbo].[Settings] ON
        '''INSERT [dbo].[Settings] ([SettingID], [SettingName], [SettingValue]) VALUES (2, N&apos;IsMultiExDateAllowed&apos;, N&apos;false&apos;)
        '''INSERT [dbo].[Settings] ([SettingID], [SettingName], [SettingValue]) VALUES (3, N&apos;IsPacketDefault&apos;, N&apos;false&apos;)
        '''INSERT [dbo].[Settings] ([SettingID], [SettingName], [SettingValue]) VALUES (5, N&apos;OwenerID&apos;, N&apos;&apos;)
        '''INSERT [dbo].[Settings] ([SettingID], [SettingName], [SettingValue]) VALUES (6, N&apos;OwnerName&apos;, N&apos;&apos;)
        '''INSERT [dbo].[Settings] ([SettingID], [Settin [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property a02_05_Insert_into_Settings() As String
            Get
                Return ResourceManager.GetString("a02_05_Insert_into_Settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''/****** Object:  StoredProcedure [dbo].[sp_tbl_Invoice_Insert]    Script Date: 04/24/2017 12:40:55 ******/
        '''IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[sp_tbl_Invoice_Insert]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        '''DROP PROCEDURE [dbo].[sp_tbl_Invoice_Insert]
        ''';
        '''/****** Object:  StoredProcedure [dbo].[sp_tbl_Invoice_Update]    Script Date: 04/24/2017 12:40:55 ******/
        '''IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[sp_tbl_Invoice_Update]&apos;) AND type in (N&apos;P&apos; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property a02_06_All() As String
            Get
                Return ResourceManager.GetString("a02_06_All", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to update Version set VersoinNumber = 3.
        '''</summary>
        Friend ReadOnly Property a02_07_Update_Version_Table() As String
            Get
                Return ResourceManager.GetString("a02_07_Update_Version_Table", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /*
        '''   Sunday, September 17, 201712:20:48 PM
        '''   User: 
        '''   Server: (local)
        '''   Database: GT1
        '''   Application: 
        '''*/
        '''
        '''/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
        '''BEGIN TRANSACTION
        '''SET QUOTED_IDENTIFIER ON
        '''SET ARITHABORT ON
        '''SET NUMERIC_ROUNDABORT OFF
        '''SET CONCAT_NULL_YIELDS_NULL ON
        '''SET ANSI_NULLS ON
        '''SET ANSI_PADDING ON
        '''SET ANSI_WARNINGS ON
        '''COMMIT
        '''BEGIN TRANSACTION
        ''';
        '''ALTER TABLE dbo.Users SE [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property a02_Add_UserID_Relation_To_Services() As String
            Get
                Return ResourceManager.GetString("a02_Add_UserID_Relation_To_Services", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Aljazeera2_BEST___Copy() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Aljazeera2_BEST___Copy", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Authentication() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Authentication", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property beep_08b() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("beep_08b", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property byteStartUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("byteStartUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property delete1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Done() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Done", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Loading() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Loading", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Message() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Message", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Prev() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Prev", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property print() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property report() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("report", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property report1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("report1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property saveprint1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("saveprint1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SHL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SHL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SHR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SHR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sorry() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sorry", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property view() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("view", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Warning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Warning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
