'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WebServiceMyUpdate
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WebServiceMyUpdate.MyUpdateSoap")>  _
    Public Interface MyUpdateSoap
        
        'CODEGEN: Generating message contract since element name PCSec from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetUpdateUrl", ReplyAction:="*")>  _
        Function GetUpdateUrl(ByVal request As WebServiceMyUpdate.GetUpdateUrlRequest) As WebServiceMyUpdate.GetUpdateUrlResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetUpdateUrlRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetUpdateUrl", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WebServiceMyUpdate.GetUpdateUrlRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebServiceMyUpdate.GetUpdateUrlRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetUpdateUrlRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public AppID As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public AppVersion As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public PCSec As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AppID As Integer, ByVal AppVersion As Integer, ByVal PCSec As String)
            MyBase.New
            Me.AppID = AppID
            Me.AppVersion = AppVersion
            Me.PCSec = PCSec
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetUpdateUrlResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetUpdateUrlResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WebServiceMyUpdate.GetUpdateUrlResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebServiceMyUpdate.GetUpdateUrlResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetUpdateUrlResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetUpdateUrlResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetUpdateUrlResult As String)
            MyBase.New
            Me.GetUpdateUrlResult = GetUpdateUrlResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface MyUpdateSoapChannel
        Inherits WebServiceMyUpdate.MyUpdateSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class MyUpdateSoapClient
        Inherits System.ServiceModel.ClientBase(Of WebServiceMyUpdate.MyUpdateSoap)
        Implements WebServiceMyUpdate.MyUpdateSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WebServiceMyUpdate_MyUpdateSoap_GetUpdateUrl(ByVal request As WebServiceMyUpdate.GetUpdateUrlRequest) As WebServiceMyUpdate.GetUpdateUrlResponse Implements WebServiceMyUpdate.MyUpdateSoap.GetUpdateUrl
            Return MyBase.Channel.GetUpdateUrl(request)
        End Function
        
        Public Function GetUpdateUrl(ByVal AppID As Integer, ByVal AppVersion As Integer, ByVal PCSec As String) As String
            Dim inValue As WebServiceMyUpdate.GetUpdateUrlRequest = New WebServiceMyUpdate.GetUpdateUrlRequest()
            inValue.Body = New WebServiceMyUpdate.GetUpdateUrlRequestBody()
            inValue.Body.AppID = AppID
            inValue.Body.AppVersion = AppVersion
            inValue.Body.PCSec = PCSec
            Dim retVal As WebServiceMyUpdate.GetUpdateUrlResponse = CType(Me,WebServiceMyUpdate.MyUpdateSoap).GetUpdateUrl(inValue)
            Return retVal.Body.GetUpdateUrlResult
        End Function
    End Class
End Namespace
